// This file was automatically generated by the extractOutlines.py script. Do not edit this file by hand.

#ifndef OUTLINES_H_
#define OUTLINES_H_

#include <cstddef>

namespace Outlines {

struct Node {
    int x;
    int y;
    char action;
};

constexpr size_t BODY = 0;
constexpr size_t FRAME = 1;
constexpr size_t HUND_A = 2;
constexpr size_t HUND_B = 3;
constexpr size_t HUND_C = 4;
constexpr size_t HUND_D = 5;
constexpr size_t HUND_E = 6;
constexpr size_t HUND_F = 7;
constexpr size_t HUND_G = 8;
constexpr size_t INNER0 = 9;
constexpr size_t INNER1 = 10;
constexpr size_t INNER2 = 11;
constexpr size_t INNER3 = 12;
constexpr size_t INNER4 = 13;
constexpr size_t INNER5 = 14;
constexpr size_t INNER6 = 15;
constexpr size_t INNER8 = 16;
constexpr size_t LEFT_ARM = 17;
constexpr size_t LEFT_ARM_INNER = 18;
constexpr size_t LEFT_ARM_MID = 19;
constexpr size_t LEFT_ARM_OUTER = 20;
constexpr size_t LEFT_CRUSH = 21;
constexpr size_t LEFT_LEG_DOWN = 22;
constexpr size_t LEFT_LEG_UP = 23;
constexpr size_t LEFT_SPLAT = 24;
constexpr size_t MID0 = 25;
constexpr size_t MID1 = 26;
constexpr size_t MID2 = 27;
constexpr size_t MID3 = 28;
constexpr size_t MID4 = 29;
constexpr size_t MID5 = 30;
constexpr size_t MID6 = 31;
constexpr size_t MID7 = 32;
constexpr size_t MID8 = 33;
constexpr size_t MID9 = 34;
constexpr size_t OUTER0 = 35;
constexpr size_t OUTER1 = 36;
constexpr size_t OUTER2 = 37;
constexpr size_t OUTER3 = 38;
constexpr size_t OUTER4 = 39;
constexpr size_t OUTER5 = 40;
constexpr size_t OUTER6 = 41;
constexpr size_t OUTER7 = 42;
constexpr size_t OUTER8 = 43;
constexpr size_t OUTER9 = 44;
constexpr size_t OUTERA = 45;
constexpr size_t OUTERB = 46;
constexpr size_t RIGHT_ARM = 47;
constexpr size_t RIGHT_ARM_INNER = 48;
constexpr size_t RIGHT_ARM_MID = 49;
constexpr size_t RIGHT_ARM_OUTER = 50;
constexpr size_t RIGHT_CRUSH = 51;
constexpr size_t RIGHT_LEG_DOWN = 52;
constexpr size_t RIGHT_LEG_UP = 53;
constexpr size_t RIGHT_SPLAT = 54;
constexpr size_t TENS_A = 55;
constexpr size_t TENS_B = 56;
constexpr size_t TENS_C = 57;
constexpr size_t TENS_D = 58;
constexpr size_t TENS_E = 59;
constexpr size_t TENS_F = 60;
constexpr size_t TENS_G = 61;
constexpr size_t THOU_A = 62;
constexpr size_t THOU_B = 63;
constexpr size_t THOU_C = 64;
constexpr size_t THOU_D = 65;
constexpr size_t THOU_E = 66;
constexpr size_t THOU_F = 67;
constexpr size_t THOU_G = 68;
constexpr size_t UNIT_A = 69;
constexpr size_t UNIT_B = 70;
constexpr size_t UNIT_C = 71;
constexpr size_t UNIT_D = 72;
constexpr size_t UNIT_E = 73;
constexpr size_t UNIT_F = 74;
constexpr size_t UNIT_G = 75;
constexpr size_t COUNT = 76;
extern const Node* ALL_OUTLINES[COUNT];

}  // namespace Outlines

#endif  // OUTLINES_H_
